### ISSUE TITLE
好像新的翻译还没上？获取的词典找不到绮良良

### ISSUE THREAD

**Issue by CanglongCl** [UIGF-org/UIGF-API#4]

**Comment by Masterain98** [comment]
fixed 
```
{
  "item_id": 10000061,
  "lang": [
    "zh-cn"
  ]
}
```

**Comment by DGCK81LNN** [comment]
UIGF API 的词典会在游戏版本更新后第一时间更新吗？我的程序会在每次卡池更新后 1 个小时抓取全部词典，这样才能尽快允许用户以 UIGF v2.3 格式导出记录。

如果 ID 是从游戏本体中获取的，那及时更新词典可能会有些困难

**Comment by DGCK81LNN** [comment]
看了下源代码，原来是从 [gitlab:Dimbreath/AnimeGameData](https://gitlab.com/Dimbreath/AnimeGameData) 获取的？那边的 commit 记录看起来都是提前于版本更新/卡池刷新的，应该没问题，只要 UIGF 这边及时更新就行
