### ISSUE TITLE
api.uigf.org connection time out from china mainland

### ISSUE THREAD

**Issue by DGCK81LNN** [UIGF-org/UIGF-API#5]
挂了梯子就能访问，不挂梯子总是超时，这个要是都能被墙我可真的服了

**Comment by Masterain98** [comment]
CDN 节点被墙了，暂时先换到了 Cloudflare，应该会稍微好那么一点。稍晚可以加一个反代节点吧。

**Comment by Masterain98** [comment]
Fixed
![image](https://github.com/UIGF-org/UIGF-API/assets/10614984/077c4ece-36ee-41b3-9ffa-2c763271cd0d)
