### ISSUE TITLE
磐岩结绿不同语言物品ID不统一，迪奥娜缺少日文译名，旅行者部分语言译名分男女

### ISSUE THREAD

**Issue by DGCK81LNN** [UIGF-org/UIGF-API#6]
通过以下代码

~~~js
/** @type {{ [lang: string]: { [name: string]: number } }} */
const dicts = await GET_DICTS() // （略）
const test = {}
for (const [lang, dictPromise] of Object.entries(dictPromises)) {
  const dict = await dictPromise
  for (const [name, id] of Object.entries(dict)) {
   if (!test[id]) test[id] = {}
    test[id][lang] = name
  }
}
const langs = Object.keys(dictPromises)
const tsv = [
  ["item_id", ...langs],
  ...Object.entries(test).map(([id, names]) => [
    id,
    ...langs.map(lang => names[lang] || ""),
  ]).filter(a => a.includes("")),
]
  .map(line => line.join("\t"))
  .join("\n")
writeFileSync("~test.tsv", tsv)
~~~

发现原神物品翻译中存在下列空缺：

item_id | chs | cht | de | en | es | fr | id | jp | kr | pt | ru | th | vi
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
11505 | 磐岩结绿 |   |   |   |   |   |   | 磐岩結緑 | 반암결록 |   | Драгоценный омут |   | Bàn Nham Kết Lục
11506 |   | 磐岩結綠 | Moosgrüner Fels | Primordial Jade Cutter | Cortador de Jade Primordial | Coupeur de jade primordial | Primordial Jade Cutter | 磐岩の緑 | 이끼 대검 | Cortador de Jade Primordial | Древний Нефритовый Резак | Primordial Jade Cutter | Nham Kết Lục
11507 |   | 憑虛 | Gefäß der Leere | One Side | Destino Vacío | Destin du néant | One Side | 虚構 | 공허한 운명 | Um Lado | Одна Сторона | One Side | Hư Vô
12505 |   | 砥厄魚 | Urzeitliches Jadeschwert | Primordial Jade Greatsword | Espada de Jade Inicial | Grande épée de jade primordial | Primordial Jade Greatsword | 美玉魚 | 고래 비녀 | Espada de Jade Primordial | Древний Нефритовый Двуручный Меч | Primordial Jade Greatsword | Đề Ách Ngư
12506 |   | 異史 | Anderer Verlauf | The Other Side | Historia Diferente | Histoire secondaire | Historia Diferente | 異史 | 괴사 | O Outro Lado | Другая Сторона | The Other Side | Dị Sử
13506 |   | 弑主 | Göttermörder | Deicide | Cazador de Dioses | Déicide | Deicide | レジサイド | 주신 학살창 | Deicida | Богоубийство | Deicide | Sát Chủ
14503 |   | 散佚的敘事詩 | Ballade des Verlusts | Lost Ballade | Balada Perdida | Ballade perdue | Lost Ballade | 散逸した叙事詩 | 산실된 서사시 | Poema Perdido | Утерянная Баллада | Lost Ballade | Bài Thơ Kể Chuyện
15504 |   | 昆吾墜龍 | Kunwus Drachenschlächter | Kunwu's Wyrmbane | Cazador de Dragones de Kunwu | Wyrmbane de Kunwu | Kunwu's Wyrmbane | 昆吾の堕龍 | 곤오추룡 | Caça-Dragões de Kunwu | Убийца Драконов Кунву | Kunwu's Wyrmbane | Rồng Kunwu
15505 |   | 懸黎千鈞 | Urzeitlicher Jadebogen | Primordial Jade Vista | Vista de Jade Primordial | Vue de jade primordial | Primordial Jade Vista | 高価なオーブ | 현려천균 | Vista da Jade Primordial | Древняя Нефритовая Виста | Primordial Jade Vista | Cung Huyền Lê
15506 |   | 破鏡 | Zerbrochener Spiegel | Mirror Breaker | Espejo Roto | Briseur de mirroire | Mirror Breaker | 壊れた鏡 | 부서진 거울 | Quebrador de Espelhos | Разбитое зеркало | Mirror Breaker | Gương Vỡ
10000005 |   |   | Reisender |   | Viajero | Voyageur |   |   |   |   | Путешественник |   |  
10000039 | 迪奥娜 | 迪奧娜 | Diona | Diona | Diona | Diona | Diona |   | 디오나 | Diona | Диона | Diona | Diona

其中：

  * 对于**磐岩结绿**，`11505` 一行有值的均为其正确译名，`11506` 一行对应的日、韩、俄、越均为错误译名，但 `11506` 的其余语言译名均正确。鉴于只有 `11505` 有简体中文译名，建议弃用 ID `11506`，全部统一至 `11505`（？）
  * `11507`、`12505`、`12506`、`13506`、`14503`、`15504`、`15505`、`15506` 似乎均为未实装物品，可暂时忽略
  * `10000005` 一行为部分区分阴阳性词的语言中**男**旅行者的译名，而 `10000007` 为**女**旅行者或不区分性别的语言中旅行者的译名
  * 迪奥娜的日文译名应为“**ディオナ**”

**Comment by DGCK81LNN** [comment]
林尼之类的翻译还没更新，这 UIGF-API 是没法用了，这下不得不改成从 [Snap.Metadata](https://github.com/DGP-Studio/Snap.Metadata/tree/main) 获取翻译了🤣，那边也没出现本 issue 提到的问题

**Comment by Masterain98** [comment]
- [x] 磐岩结绿
- [x] 迪奥娜的日文译名应为“ディオナ”
- [x] 4.0 更新

**Comment by DGCK81LNN** [comment]
感谢

**Comment by DGCK81LNN** [comment]
现在磐岩结绿似乎又出问题了，还是跟之前的情况一样 @Masterain98 

item_id | chs | cht | de | en | es | fr | id | jp | kr | pt | ru | th | vi
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
11505 | 磐岩结绿 | - | - | - | - | - | - | 磐岩結緑 | 반암결록 | - | Драгоценный омут | - | Bàn Nham Kết Lục
11506 | - | 磐岩結綠 | Moosgrüner Fels | Primordial Jade Cutter | Cortador de Jade Primordial | Coupeur de jade primordial | Primordial Jade Cutter | 磐岩の緑 | 이끼 대검 | Cortador de Jade Primordial | Древний Нефритовый Резак | Primordial Jade Cutter | Nham Kết Lục
