### ISSUE TITLE
星铁api接口数据过时

### ISSUE THREAD

**Issue by frankcwl** [UIGF-org/UIGF-API#7]
数据还停留在1.4版本
<details>
<summary>以<code>/dict/starrail/chs.json</code>为例</summary>
<pre><code>{
    "三月七": 1001,
    "丹恒": 1002,
    "姬子": 1003,
    "瓦尔特": 1004,
    "卡芙卡": 1005,
    "银狼": 1006,
    "阿兰": 1008,
    "艾丝妲": 1009,
    "黑塔": 1013,
    "布洛妮娅": 1101,
    "希儿": 1102,
    "希露瓦": 1103,
    "杰帕德": 1104,
    "娜塔莎": 1105,
    "佩拉": 1106,
    "克拉拉": 1107,
    "桑博": 1108,
    "虎克": 1109,
    "玲可": 1110,
    "卢卡": 1111,
    "托帕&账账": 1112,
    "青雀": 1201,
    "停云": 1202,
    "罗刹": 1203,
    "景元": 1204,
    "刃": 1205,
    "素裳": 1206,
    "驭空": 1207,
    "符玄": 1208,
    "彦卿": 1209,
    "桂乃芬": 1210,
    "白露": 1211,
    "镜流": 1212,
    "丹恒•饮月": 1213,
    "{NICKNAME}": 8004,
    "锋镝": 20000,
    "物穰": 20001,
    "天倾": 20002,
    "琥珀": 20003,
    "幽邃": 20004,
    "齐颂": 20005,
    "智库": 20006,
    "离弦": 20007,
    "嘉果": 20008,
    "乐圮": 20009,
    "戍御": 20010,
    "渊环": 20011,
    "轮契": 20012,
    "灵钥": 20013,
    "相抗": 20014,
    "蕃息": 20015,
    "俱殁": 20016,
    "开疆": 20017,
    "匿影": 20018,
    "调和": 20019,
    "睿见": 20020,
    "一场术后对话": 21000,
    "晚安与睡颜": 21001,
    "余生的第一天": 21002,
    "唯有沉默": 21003,
    "记忆中的模样": 21004,
    "鼹鼠党欢迎你": 21005,
    "「我」的诞生": 21006,
    "同一种心情": 21007,
    "猎物的视线": 21008,
    "朗道的选择": 21009,
    "论剑": 21010,
    "与行星相会": 21011,
    "秘密誓心": 21012,
    "别让世界静下来": 21013,
    "此时恰好": 21014,
    "决心如汗珠般闪耀": 21015,
    "宇宙市场趋势": 21016,
    "点个关注吧！": 21017,
    "舞！舞！舞！": 21018,
    "在蓝天下": 21019,
    "天才们的休憩": 21020,
    "等价交换": 21021,
    "延长记号": 21022,
    "我们是地火": 21023,
    "春水初生": 21024,
    "过往未来": 21025,
    "汪！散步时间！": 21026,
    "早餐的仪式感": 21027,
    "暖夜不会漫长": 21028,
    "后会有期": 21029,
    "这就是我啦！": 21030,
    "重返幽冥": 21031,
    "镂月裁云之意": 21032,
    "无处可逃": 21033,
    "今日亦是和平的一日": 21034,
    "新手任务开始前": 22000,
    "银河铁道之夜": 23000,
    "于夜色中": 23001,
    "无可取代的东西": 23002,
    "但战斗还未结束": 23003,
    "以世界之名": 23004,
    "制胜的瞬间": 23005,
    "只需等待": 23006,
    "雨一直下": 23007,
    "棺的回响": 23008,
    "到不了的彼岸": 23009,
    "拂晓之前": 23010,
    "她已闭上双眼": 23011,
    "如泥酣眠": 23012,
    "时节不居": 23013,
    "此身为剑": 23014,
    "比阳光更明亮的": 23015,
    "烦恼着，幸福着": 23016,
    "记一位星神的陨落": 24000,
    "星海巡航": 24001,
    "记忆的质料": 24002,
    "孤独的疗愈": 24003
}</code></pre>
</details>

**Comment by Masterain98** [comment]
Updated

```
{
  "三月七": 1001,
  "丹恒": 1002,
  "姬子": 1003,
  "瓦尔特": 1004,
  "卡芙卡": 1005,
  "银狼": 1006,
  "阿兰": 1008,
  "艾丝妲": 1009,
  "黑塔": 1013,
  "布洛妮娅": 1101,
  "希儿": 1102,
  "希露瓦": 1103,
  "杰帕德": 1104,
  "娜塔莎": 1105,
  "佩拉": 1106,
  "克拉拉": 1107,
  "桑博": 1108,
  "虎克": 1109,
  "玲可": 1110,
  "卢卡": 1111,
  "托帕&账账": 1112,
  "青雀": 1201,
  "停云": 1202,
  "罗刹": 1203,
  "景元": 1204,
  "刃": 1205,
  "素裳": 1206,
  "驭空": 1207,
  "符玄": 1208,
  "彦卿": 1209,
  "桂乃芬": 1210,
  "白露": 1211,
  "镜流": 1212,
  "丹恒•饮月": 1213,
  "雪衣": 1214,
  "寒鸦": 1215,
  "藿藿": 1217,
  "银枝": 1302,
  "阮•梅": 1303,
  "真理医生": 1305,
  "{NICKNAME}": 8004,
  "锋镝": 20000,
  "物穰": 20001,
  "天倾": 20002,
  "琥珀": 20003,
  "幽邃": 20004,
  "齐颂": 20005,
  "智库": 20006,
  "离弦": 20007,
  "嘉果": 20008,
  "乐圮": 20009,
  "戍御": 20010,
  "渊环": 20011,
  "轮契": 20012,
  "灵钥": 20013,
  "相抗": 20014,
  "蕃息": 20015,
  "俱殁": 20016,
  "开疆": 20017,
  "匿影": 20018,
  "调和": 20019,
  "睿见": 20020,
  "一场术后对话": 21000,
  "晚安与睡颜": 21001,
  "余生的第一天": 21002,
  "唯有沉默": 21003,
  "记忆中的模样": 21004,
  "鼹鼠党欢迎你": 21005,
  "「我」的诞生": 21006,
  "同一种心情": 21007,
  "猎物的视线": 21008,
  "朗道的选择": 21009,
  "论剑": 21010,
  "与行星相会": 21011,
  "秘密誓心": 21012,
  "别让世界静下来": 21013,
  "此时恰好": 21014,
  "决心如汗珠般闪耀": 21015,
  "宇宙市场趋势": 21016,
  "点个关注吧！": 21017,
  "舞！舞！舞！": 21018,
  "在蓝天下": 21019,
  "天才们的休憩": 21020,
  "等价交换": 21021,
  "延长记号": 21022,
  "我们是地火": 21023,
  "春水初生": 21024,
  "过往未来": 21025,
  "汪！散步时间！": 21026,
  "早餐的仪式感": 21027,
  "暖夜不会漫长": 21028,
  "后会有期": 21029,
  "这就是我啦！": 21030,
  "重返幽冥": 21031,
  "镂月裁云之意": 21032,
  "无处可逃": 21033,
  "今日亦是和平的一日": 21034,
  "新手任务开始前": 22000,
  "嘿，我在这儿": 22001,
  "银河铁道之夜": 23000,
  "于夜色中": 23001,
  "无可取代的东西": 23002,
  "但战斗还未结束": 23003,
  "以世界之名": 23004,
  "制胜的瞬间": 23005,
  "只需等待": 23006,
  "雨一直下": 23007,
  "棺的回响": 23008,
  "到不了的彼岸": 23009,
  "拂晓之前": 23010,
  "她已闭上双眼": 23011,
  "如泥酣眠": 23012,
  "时节不居": 23013,
  "此身为剑": 23014,
  "比阳光更明亮的": 23015,
  "烦恼着，幸福着": 23016,
  "惊魂夜": 23017,
  "片刻，留在眼底": 23018,
  "镜中故我": 23019,
  "纯粹思维的洗礼": 23020,
  "记一位星神的陨落": 24000,
  "星海巡航": 24001,
  "记忆的质料": 24002,
  "孤独的疗愈": 24003
}
```
