### ISSUE TITLE
Support Zenless Zone Zero

### ISSUE THREAD

**Issue by Masterain98** [UIGF-org/UIGF-API#9]

**Comment by seriaati** [comment]
Translation API can be supported with the help of Zenless Data:
w-engine and bangboo IDs are located in here: https://git.mero.moe/dimbreath/ZenlessData/raw/branch/master/FileCfg/ItemTemplateTb.json
agent IDs are located in here: https://git.mero.moe/dimbreath/ZenlessData/raw/branch/master/FileCfg/AvatarBaseTemplateTb.json

Example w-engine entry:
`NGPCCDGBLLK` is the w-engine ID, `EAAFCGPDFAA` is the text map key
```json
{
      "NGPCCDGBLLK": 12004,
      "EAAFCGPDFAA": "Item_Weapon_B_Common_04_Name",
      "GNAGJHPOCIO": 2,
      "IMGCLANBHDG": 5,
      ...
}
```

Example bangboo entry:
`NGPCCDGBLLK` is bangboo ID, `EAAFCGPDFAA` is text map key.
```json
{
      "NGPCCDGBLLK": 53011,
      "EAAFCGPDFAA": "Bangboo_Name_53011",
      "GNAGJHPOCIO": 3,
      "IMGCLANBHDG": 8,
      ...
}
```

Example agent entry:
`NGPCCDGBLLK` is agent ID, `EAAFCGPDFAA` is text map key.
```json
{
      "NGPCCDGBLLK": 1011,
      "OBMHHBOOCJK": "Avatar_Female_Size02_Anbi_En",
      "EAAFCGPDFAA": "Avatar_Female_Size02_Anbi",
      "JMBNNNBMAOE": "Avatar_Female_Size02_Anbi_FullName",
      "HCCJDJEHIPA": "anbi",
      ...
}
```

With the text map key, go to any text map file, e.g. https://git.mero.moe/dimbreath/ZenlessData/raw/branch/master/TextMap/TextMap_CHTTemplateTb.json
and obtain the item name with the text map key.
